name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t mentoringkc/applialacon:latest -t mentoringkc/applialacon:$(date +%s) -f MongoContainerAPI/Dockerfile .
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push mentoringkc/applialacon:latest
      
  deploy:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_PEM_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: Connect to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PEM_KEY }}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH ${{ vars.EC2_USER }}@${{ vars.EC2_HOSTNAME }} "cd /opt/alacon && docker compose down && docker compose pull && docker compose up -d"
    
